<a href="https://colab.research.google.com/github/Enmoth/Games/blob/main/Games.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import gdown

In [3]:
!gdown 12WqReU95ah37wOYB6LB9u3-M77trmQnO

Downloading...
From: https://drive.google.com/uc?id=12WqReU95ah37wOYB6LB9u3-M77trmQnO
To: /content/games.csv
100% 2.87M/2.87M [00:00<00:00, 181MB/s]

In [4]:
df = pd.read_csv('games.csv')

In [5]:
df

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,1507,Back to the Future: The Game,"Dec 22, 2010",['Telltale Games'],3.2,94,94,"['Adventure', 'Point-and-Click']",Back to the Future: The Game is one of Telltal...,['Very enjoyable game. The story adds onto the...,763,5,223,67
1508,1508,Team Sonic Racing,"May 21, 2019","['Sumo Digital', 'Sega']",2.9,264,264,"['Arcade', 'Racing']",Team Sonic Racing combines the best elements o...,"['jogo morto mas bom', 'not my cup of tea', ""C...",1.5K,49,413,107
1509,1509,Dragon's Dogma,"May 22, 2012",['Capcom'],3.7,210,210,"['Brawler', 'RPG']","Set in a huge open world, Dragon’s Dogma: Dark...","['Underrated.', 'A grandes rasgos, es como un ...",1.1K,45,487,206
1510,1510,Baldur's Gate 3,"Oct 06, 2020",['Larian Studios'],4.1,165,165,"['Adventure', 'RPG', 'Strategy', 'Tactical', '...","An ancient evil has returned to Baldur's Gate,...",['Bu türe bu oyunla girmeye çalışmak hataydı s...,269,79,388,602
1511,1511,The LEGO Movie Videogame,"Feb 04, 2014","['WB Games', 'TT Fusion']",2.8,184,184,"['Adventure', 'Puzzle']",Join Emmet and an unlikely group of resistance...,"['Legal', 'Pretty Average Lego Game But It Was...",1.7K,11,239,73

In [6]:
df = df.drop('Unnamed: 0', axis=1)

In [7]:
df

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,Back to the Future: The Game,"Dec 22, 2010",['Telltale Games'],3.2,94,94,"['Adventure', 'Point-and-Click']",Back to the Future: The Game is one of Telltal...,['Very enjoyable game. The story adds onto the...,763,5,223,67
1508,Team Sonic Racing,"May 21, 2019","['Sumo Digital', 'Sega']",2.9,264,264,"['Arcade', 'Racing']",Team Sonic Racing combines the best elements o...,"['jogo morto mas bom', 'not my cup of tea', ""C...",1.5K,49,413,107
1509,Dragon's Dogma,"May 22, 2012",['Capcom'],3.7,210,210,"['Brawler', 'RPG']","Set in a huge open world, Dragon’s Dogma: Dark...","['Underrated.', 'A grandes rasgos, es como un ...",1.1K,45,487,206
1510,Baldur's Gate 3,"Oct 06, 2020",['Larian Studios'],4.1,165,165,"['Adventure', 'RPG', 'Strategy', 'Tactical', '...","An ancient evil has returned to Baldur's Gate,...",['Bu türe bu oyunla girmeye çalışmak hataydı s...,269,79,388,602
1511,The LEGO Movie Videogame,"Feb 04, 2014","['WB Games', 'TT Fusion']",2.8,184,184,"['Adventure', 'Puzzle']",Join Emmet and an unlikely group of resistance...,"['Legal', 'Pretty Average Lego Game But It Was...",1.7K,11,239,73

In [8]:
df = df.drop('Backlogs', axis=1)

In [9]:
df

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Wishlist
0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.8K
1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,3.6K
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,2.6K
3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,1.8K
4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,2.3K
...,...,...,...,...,...,...,...,...,...,...,...,...
1507,Back to the Future: The Game,"Dec 22, 2010",['Telltale Games'],3.2,94,94,"['Adventure', 'Point-and-Click']",Back to the Future: The Game is one of Telltal...,['Very enjoyable game. The story adds onto the...,763,5,67
1508,Team Sonic Racing,"May 21, 2019","['Sumo Digital', 'Sega']",2.9,264,264,"['Arcade', 'Racing']",Team Sonic Racing combines the best elements o...,"['jogo morto mas bom', 'not my cup of tea', ""C...",1.5K,49,107
1509,Dragon's Dogma,"May 22, 2012",['Capcom'],3.7,210,210,"['Brawler', 'RPG']","Set in a huge open world, Dragon’s Dogma: Dark...","['Underrated.', 'A grandes rasgos, es como un ...",1.1K,45,206
1510,Baldur's Gate 3,"Oct 06, 2020",['Larian Studios'],4.1,165,165,"['Adventure', 'RPG', 'Strategy', 'Tactical', '...","An ancient evil has returned to Baldur's Gate,...",['Bu türe bu oyunla girmeye çalışmak hataydı s...,269,79,602
1511,The LEGO Movie Videogame,"Feb 04, 2014","['WB Games', 'TT Fusion']",2.8,184,184,"['Adventure', 'Puzzle']",Join Emmet and an unlikely group of resistance...,"['Legal', 'Pretty Average Lego Game But It Was...",1.7K,11,73

In [10]:
def convert_value(value):
    if 'k' in value.lower():
        return float(value.lower().replace('k', '')) * 1000
    else:
        try:
            return float(value)
        except ValueError:
            return value

In [11]:
df['Plays'] = df['Plays'].apply(convert_value)

In [12]:
df

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Wishlist
0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17000.0,3.8K,4.8K
1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21000.0,3.2K,3.6K
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30000.0,2.5K,2.6K
3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28000.0,679,1.8K
4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21000.0,2.4K,2.3K
...,...,...,...,...,...,...,...,...,...,...,...,...
1507,Back to the Future: The Game,"Dec 22, 2010",['Telltale Games'],3.2,94,94,"['Adventure', 'Point-and-Click']",Back to the Future: The Game is one of Telltal...,['Very enjoyable game. The story adds onto the...,763.0,5,67
1508,Team Sonic Racing,"May 21, 2019","['Sumo Digital', 'Sega']",2.9,264,264,"['Arcade', 'Racing']",Team Sonic Racing combines the best elements o...,"['jogo morto mas bom', 'not my cup of tea', ""C...",1500.0,49,107
1509,Dragon's Dogma,"May 22, 2012",['Capcom'],3.7,210,210,"['Brawler', 'RPG']","Set in a huge open world, Dragon’s Dogma: Dark...","['Underrated.', 'A grandes rasgos, es como un ...",1100.0,45,206
1510,Baldur's Gate 3,"Oct 06, 2020",['Larian Studios'],4.1,165,165,"['Adventure', 'RPG', 'Strategy', 'Tactical', '...","An ancient evil has returned to Baldur's Gate,...",['Bu türe bu oyunla girmeye çalışmak hataydı s...,269.0,79,602
1511,The LEGO Movie Videogame,"Feb 04, 2014","['WB Games', 'TT Fusion']",2.8,184,184,"['Adventure', 'Puzzle']",Join Emmet and an unlikely group of resistance...,"['Legal', 'Pretty Average Lego Game But It Was...",1700.0,11,73

In [13]:
df['Playing'] = df['Playing'].apply(convert_value)
df['Wishlist'] = df['Wishlist'].apply(convert_value)

In [14]:
df['Times Listed'] = df['Times Listed'].apply(convert_value)
df['Number of Reviews'] = df['Number of Reviews'].apply(convert_value)

In [15]:
df

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Wishlist
0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3900.0,3900.0,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17000.0,3800.0,4800.0
1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2900.0,2900.0,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21000.0,3200.0,3600.0
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4300.0,4300.0,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30000.0,2500.0,2600.0
3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3500.0,3500.0,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28000.0,679.0,1800.0
4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3000.0,3000.0,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21000.0,2400.0,2300.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1507,Back to the Future: The Game,"Dec 22, 2010",['Telltale Games'],3.2,94.0,94.0,"['Adventure', 'Point-and-Click']",Back to the Future: The Game is one of Telltal...,['Very enjoyable game. The story adds onto the...,763.0,5.0,67.0
1508,Team Sonic Racing,"May 21, 2019","['Sumo Digital', 'Sega']",2.9,264.0,264.0,"['Arcade', 'Racing']",Team Sonic Racing combines the best elements o...,"['jogo morto mas bom', 'not my cup of tea', ""C...",1500.0,49.0,107.0
1509,Dragon's Dogma,"May 22, 2012",['Capcom'],3.7,210.0,210.0,"['Brawler', 'RPG']","Set in a huge open world, Dragon’s Dogma: Dark...","['Underrated.', 'A grandes rasgos, es como un ...",1100.0,45.0,206.0
1510,Baldur's Gate 3,"Oct 06, 2020",['Larian Studios'],4.1,165.0,165.0,"['Adventure', 'RPG', 'Strategy', 'Tactical', '...","An ancient evil has returned to Baldur's Gate,...",['Bu türe bu oyunla girmeye çalışmak hataydı s...,269.0,79.0,602.0
1511,The LEGO Movie Videogame,"Feb 04, 2014","['WB Games', 'TT Fusion']",2.8,184.0,184.0,"['Adventure', 'Puzzle']",Join Emmet and an unlikely group of resistance...,"['Legal', 'Pretty Average Lego Game But It Was...",1700.0,11.0,73.0

In [16]:
# Calcular a soma total de plays para cada gênero
genre_counts = df.groupby('Genres')['Plays'].sum().reset_index()

# Ordenar o DataFrame em ordem decrescente com base nas somas de plays
genre_counts_sorted = genre_counts.sort_values('Plays', ascending=False)

In [17]:
print(genre_counts_sorted)

                                                Genres      Plays
119                               ['Adventure', 'RPG']  1142501.0
91                           ['Adventure', 'Platform']   886734.0
128                           ['Adventure', 'Shooter']   611379.0
245                                        ['Shooter']   574977.0
118        ['Adventure', 'RPG', 'Turn Based Strategy']   406800.0
..                                                 ...        ...
228       ['RPG', 'Simulator', 'Strategy', 'Tactical']      279.0
41   ['Adventure', 'Fighting', 'Shooter', 'Simulato...      186.0
145             ['Arcade', 'Indie', 'Music', 'Puzzle']      185.0
43   ['Adventure', 'Indie', 'Music', 'Platform', 'P...      183.0
198  ['Indie', 'RPG', 'Strategy', 'Tactical', 'Turn...       16.0

[255 rows x 2 columns]

In [18]:
df_genre_mix = genre_counts_sorted

In [19]:
df_genre_mix

                                                Genres      Plays
119                               ['Adventure', 'RPG']  1142501.0
91                           ['Adventure', 'Platform']   886734.0
128                           ['Adventure', 'Shooter']   611379.0
245                                        ['Shooter']   574977.0
118        ['Adventure', 'RPG', 'Turn Based Strategy']   406800.0
..                                                 ...        ...
228       ['RPG', 'Simulator', 'Strategy', 'Tactical']      279.0
41   ['Adventure', 'Fighting', 'Shooter', 'Simulato...      186.0
145             ['Arcade', 'Indie', 'Music', 'Puzzle']      185.0
43   ['Adventure', 'Indie', 'Music', 'Platform', 'P...      183.0
198  ['Indie', 'RPG', 'Strategy', 'Tactical', 'Turn...       16.0

[255 rows x 2 columns]

In [28]:
genre_counts = df['Genres'].value_counts().reset_index()
genre_counts.columns = ['Genre', 'Count']
genre_counts_sorted = genre_counts.sort_values('Count', ascending=False)

df_genre_mix_count = genre_counts_sorted

print(genre_counts_sorted)

                                               Genre  Count
0                               ['Adventure', 'RPG']    154
1                          ['Adventure', 'Platform']    107
2                           ['Adventure', 'Shooter']     82
3                                        ['Shooter']     72
4        ['Adventure', 'RPG', 'Turn Based Strategy']     48
..                                               ...    ...
172   ['Adventure', 'Arcade', 'Platform', 'Shooter']      1
171  ['Real Time Strategy', 'Simulator', 'Strategy']      1
170      ['Adventure', 'Brawler', 'Fighting', 'RPG']      1
169                ['Fighting', 'Racing', 'Shooter']      1
254            ['Simulator', 'Strategy', 'Tactical']      1

[255 rows x 2 columns]

In [29]:
df_copy = df.copy()

df_copy['Genres'] = df_copy['Genres'].str.split(',')
df_copy = df_copy.explode('Genres')
df_copy['Genres'] = df_copy['Genres'].str.replace(r"[\[\]']", "").str.strip()
genre_counts = df_copy['Genres'].value_counts().reset_index()
genre_counts.columns = ['Genre', 'Count']
genre_counts['Total Plays'] = df_copy.groupby('Genres')['Plays'].sum().values
genre_counts_sorted = genre_counts.sort_values('Total Plays', ascending=False)

df_genre_plays = genre_counts_sorted

print(genre_counts_sorted)

                  Genre  Count  Total Plays
1                   RPG    523    6637829.0
14      Point-and-Click     46    3292840.0
17                Sport     25    2655574.0
10               Arcade     73    2356470.0
6               Brawler    159    1550927.0
3              Platform    329    1023390.0
12         Visual Novel     71     932232.0
18    Card & Board Game     16     717260.0
20          Quiz/Trivia      4     698759.0
22                           3     676584.0
2               Shooter    353     376753.0
5                Puzzle    176     368099.0
15               Racing     42     302274.0
23              Pinball      1     253633.0
21                 MOBA      3     223849.0
11             Fighting     72     185317.0
19   Real Time Strategy     10     149433.0
8             Simulator    125      67881.0
4                 Indie    284      57747.0
16                Music     25      38600.0
7              Strategy    142      30500.0
13             Tactical     50      10100.0
9   Turn Based Strategy     99       1600.0
0             Adventure   1014       1237.0

<ipython-input-29-9689b0faf4a3>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df_copy['Genres'] = df_copy['Genres'].str.replace(r"[\[\]']", "").str.strip()

In [30]:
df

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Wishlist
0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3900.0,3900.0,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17000.0,3800.0,4800.0
1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2900.0,2900.0,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21000.0,3200.0,3600.0
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4300.0,4300.0,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30000.0,2500.0,2600.0
3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3500.0,3500.0,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28000.0,679.0,1800.0
4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3000.0,3000.0,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21000.0,2400.0,2300.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1507,Back to the Future: The Game,"Dec 22, 2010",['Telltale Games'],3.2,94.0,94.0,"['Adventure', 'Point-and-Click']",Back to the Future: The Game is one of Telltal...,['Very enjoyable game. The story adds onto the...,763.0,5.0,67.0
1508,Team Sonic Racing,"May 21, 2019","['Sumo Digital', 'Sega']",2.9,264.0,264.0,"['Arcade', 'Racing']",Team Sonic Racing combines the best elements o...,"['jogo morto mas bom', 'not my cup of tea', ""C...",1500.0,49.0,107.0
1509,Dragon's Dogma,"May 22, 2012",['Capcom'],3.7,210.0,210.0,"['Brawler', 'RPG']","Set in a huge open world, Dragon’s Dogma: Dark...","['Underrated.', 'A grandes rasgos, es como un ...",1100.0,45.0,206.0
1510,Baldur's Gate 3,"Oct 06, 2020",['Larian Studios'],4.1,165.0,165.0,"['Adventure', 'RPG', 'Strategy', 'Tactical', '...","An ancient evil has returned to Baldur's Gate,...",['Bu türe bu oyunla girmeye çalışmak hataydı s...,269.0,79.0,602.0
1511,The LEGO Movie Videogame,"Feb 04, 2014","['WB Games', 'TT Fusion']",2.8,184.0,184.0,"['Adventure', 'Puzzle']",Join Emmet and an unlikely group of resistance...,"['Legal', 'Pretty Average Lego Game But It Was...",1700.0,11.0,73.0

In [31]:
df_genre_mix_count

                                               Genre  Count
0                               ['Adventure', 'RPG']    154
1                          ['Adventure', 'Platform']    107
2                           ['Adventure', 'Shooter']     82
3                                        ['Shooter']     72
4        ['Adventure', 'RPG', 'Turn Based Strategy']     48
..                                               ...    ...
172   ['Adventure', 'Arcade', 'Platform', 'Shooter']      1
171  ['Real Time Strategy', 'Simulator', 'Strategy']      1
170      ['Adventure', 'Brawler', 'Fighting', 'RPG']      1
169                ['Fighting', 'Racing', 'Shooter']      1
254            ['Simulator', 'Strategy', 'Tactical']      1

[255 rows x 2 columns]

In [32]:
df_genre_plays

                  Genre  Count  Total Plays
1                   RPG    523    6637829.0
14      Point-and-Click     46    3292840.0
17                Sport     25    2655574.0
10               Arcade     73    2356470.0
6               Brawler    159    1550927.0
3              Platform    329    1023390.0
12         Visual Novel     71     932232.0
18    Card & Board Game     16     717260.0
20          Quiz/Trivia      4     698759.0
22                           3     676584.0
2               Shooter    353     376753.0
5                Puzzle    176     368099.0
15               Racing     42     302274.0
23              Pinball      1     253633.0
21                 MOBA      3     223849.0
11             Fighting     72     185317.0
19   Real Time Strategy     10     149433.0
8             Simulator    125      67881.0
4                 Indie    284      57747.0
16                Music     25      38600.0
7              Strategy    142      30500.0
13             Tactical     50      10100.0
9   Turn Based Strategy     99       1600.0
0             Adventure   1014       1237.0

In [34]:
df_genre_mix

                                                Genres      Plays
119                               ['Adventure', 'RPG']  1142501.0
91                           ['Adventure', 'Platform']   886734.0
128                           ['Adventure', 'Shooter']   611379.0
245                                        ['Shooter']   574977.0
118        ['Adventure', 'RPG', 'Turn Based Strategy']   406800.0
..                                                 ...        ...
228       ['RPG', 'Simulator', 'Strategy', 'Tactical']      279.0
41   ['Adventure', 'Fighting', 'Shooter', 'Simulato...      186.0
145             ['Arcade', 'Indie', 'Music', 'Puzzle']      185.0
43   ['Adventure', 'Indie', 'Music', 'Platform', 'P...      183.0
198  ['Indie', 'RPG', 'Strategy', 'Tactical', 'Turn...       16.0

[255 rows x 2 columns]